baseURL = 'https://goodiasgle-dotcom.github.io/sport-news-site/'
languageCode = 'el'
title = 'Sport News GR'
theme = ''
disableKinds = ['taxonomy', 'term', 'section']

[params]
  description = 'Τα τελευταία αθλητικά νέα από την Ελλάδα και τον κόσμο'
  author = 'Sport News GR'
